#!/bin/bash
# Flask script


function flask_env_func()
{
echo "Preparing Flask venv"
cd ~/Pulpit/Projekty/Price_scraper_3/venv/bin
source activate
cd ..
cd ..
}


function open_chrome_func()
{
google-chrome http://127.0.0.1:5000/
sleep 2
xdotool key ctrl+r
}


function test_func()
{
echo "Running tests"
flask_env_func
pytest -s -v
}


function flask_app_func()
{
test_func
echo "Running Flask app"
flask_env_func
open_chrome_func
python price_scraper_app.py
}


flask_app_func



